package dev.jlo.gamemodes.domain.opr;

import dev.jlo.gamemodes.domain.common.*;
import java.time.*;
import java.util.*;

public class OprMatch {
 private final OprConfig config; private final Instant start; private final MatchLifecycle lifecycle; public final Map<OutpostId,OutpostState> outposts=new EnumMap<>(OutpostId.class); public final Map<Team,GateState> gates=new EnumMap<>(Team.class); public final Set<UUID> expiredPlayers=new LinkedHashSet<>(); private MatchResult result; private final MatchRoster roster; private final Map<UUID,Team> teams=new HashMap<>(); private final Map<Team,Integer> scores=new EnumMap<>(Team.class); private final Map<UUID,Map<Resource,Integer>> carried=new HashMap<>(); private final Map<Team,Map<Resource,Integer>> storage=new EnumMap<>(Team.class); private final Map<UUID,Instant> cooldowns=new HashMap<>(),disconnected=new HashMap<>(),spawnProtectedUntil=new HashMap<>(),recentCombat=new HashMap<>(); private final Map<Team,Integer> tokenWallet=new EnumMap<>(Team.class),commandPostTier=new EnumMap<>(Team.class); private final Map<Team,Instant> scoreLocks=new EnumMap<>(Team.class),wardUntil=new EnumMap<>(Team.class); private final Map<Team,List<Summon>> summonsByTeam=new EnumMap<>(Team.class); private Instant now,battleStartedAt,nextScoreTick,suddenDeathUntil,portalClosedAt;
 public OprMatch(OprConfig config,Instant start){this(config,start,new MatchLifecycle(MatchPhase.WAITING));}
 public OprMatch(Instant start){this(new OprConfig(),start,new MatchLifecycle(MatchPhase.WAITING));} public OprMatch(OprConfig config,Instant start,MatchLifecycle lifecycle){this.config=config;this.start=start;this.lifecycle=lifecycle;this.now=start;this.nextScoreTick=start.plus(config.getScoreInterval());this.roster=new MatchRoster(config.getTeamCapacity(),Quorum.fixed(config.getQuorumPerTeam()));for(OutpostId x:OutpostId.values())outposts.put(x,new OutpostState(x));for(Team t:Team.values()){gates.put(t,new GateState());scores.put(t,0);tokenWallet.put(t,0);commandPostTier.put(t,1);summonsByTeam.put(t,new ArrayList<>());Map<Resource,Integer> m=new EnumMap<>(Resource.class);for(Resource r:Resource.values())m.put(r,0);storage.put(t,m);}}
 public OprConfig getConfig(){return config;} public Instant getStart(){return start;} public MatchLifecycle getLifecycle(){return lifecycle;} public Map<OutpostId,OutpostState> getOutposts(){return outposts;} public Map<Team,GateState> getGates(){return gates;} public Set<UUID> getExpiredPlayers(){return expiredPlayers;} public MatchResult getResult(){return result;}
 public Team join(UUID p){if(lifecycle.getPhase()!=MatchPhase.WAITING)throw new IllegalStateException();Team t=roster.join(p);teams.put(p,t);return t;} public Team leave(UUID p){Team t=teams.remove(p);if(t==null)return null;roster.leave(p);for(OutpostState o:outposts.values()){o.getOccupants().remove(p);if(o.getOccupants().isEmpty()){o.setEmptySince(now);o.setLastTick(now);}}carried.remove(p);disconnected.remove(p);cooldowns.remove(p);return t;}
 public void assign(UUID p,Team t){if(teams.containsKey(p))throw new IllegalStateException();teams.put(p,t);if(lifecycle.getPhase()==MatchPhase.ACTIVE)spawnProtectedUntil.put(p,(battleStartedAt!=null?battleStartedAt:now).plus(config.getSpawnProtection()));}
 public void baronessDefeated(Team t,Instant at,int deficit){long s=Math.min(150,60L+Math.max(0,deficit));scoreLocks.put(OprMatchKt.other(t),at.plusSeconds(s));} public void baronessDefeated(Team t,Instant at){baronessDefeated(t,at,0);}
 public void beginPreparation(Instant at){now=at;lifecycle.transitionTo(MatchPhase.PREPARING);} public void start(Instant at){if(!roster.hasQuorum()&&teams.size()<config.getQuorumPerTeam()*2)throw new IllegalStateException();now=at;battleStartedAt=at;for(UUID p:teams.keySet())spawnProtectedUntil.put(p,at.plus(config.getSpawnProtection()));lifecycle.transitionTo(MatchPhase.ACTIVE);nextScoreTick=at.plus(config.getScoreInterval());}
 public void enterOutpost(UUID p,OutpostId id){if(!teams.containsKey(p))throw new IllegalStateException();OutpostState o=outposts.get(id);if(o.getOccupants().isEmpty()){Team t=teams.get(p);if(o.getOwner()!=t){o.setCapturingTeam(t);o.setProgress(Duration.ZERO);}o.setLastTick(now);o.setEmptySince(null);}o.getOccupants().add(p);} public void leaveOutpost(UUID p,OutpostId id){OutpostState o=outposts.get(id);o.getOccupants().remove(p);if(o.getOccupants().isEmpty()){o.setEmptySince(now);o.setLastTick(now);}}
 public void advanceTo(Instant at){if(at.isBefore(now))throw new IllegalArgumentException();now=at;expireDisconnects(at);if(lifecycle.getPhase()!=MatchPhase.ACTIVE)return;if(suddenDeathUntil!=null){if(!at.isBefore(suddenDeathUntil))resolve(null);return;}for(OutpostState o:outposts.values())updateCapture(o,at);while(!at.isBefore(nextScoreTick)){for(OutpostState o:outposts.values()){Team owner=o.getOwner();if(owner!=null&&o.getOwnershipSince()!=null&&o.getOwnershipSince().isBefore(nextScoreTick)&&!isScoreLocked(owner,nextScoreTick))scores.put(owner,score(owner)+1);}nextScoreTick=nextScoreTick.plus(config.getScoreInterval());}Instant deadline=battleStartedAt==null?null:battleStartedAt.plus(config.getMatchDuration());if(deadline!=null&&!at.isBefore(deadline))resolveAtDeadline(at);else checkTarget();}
 private void updateCapture(OutpostState o,Instant at){Set<Team> present=new HashSet<>();for(UUID p:o.getOccupants())if(teams.containsKey(p))present.add(teams.get(p));if(present.isEmpty()){Instant es=o.getEmptySince();if(es==null){es=at;o.setEmptySince(at);}Instant prev=o.getLastTick()==null?at:o.getLastTick();Instant decay=prev.isAfter(es.plus(config.getCaptureDecayDelay()))?prev:es.plus(config.getCaptureDecayDelay());if(at.isAfter(decay)){o.setProgress(o.getProgress().minus(Duration.between(decay,at)));if(o.getProgress().isNegative())o.setProgress(Duration.ZERO);if(o.getProgress().isZero())o.setCapturingTeam(null);}o.setLastTick(at);return;}o.setEmptySince(null);if(present.size()!=1){o.setLastTick(at);return;}Team t=present.iterator().next();if(o.getOwner()==t){o.setLastTick(at);o.setProgress(Duration.ZERO);o.setCapturingTeam(null);return;}if(o.captureBlockedByWard(t,at)){o.setLastTick(at);return;}if(o.getCapturingTeam()!=t){o.setCapturingTeam(t);o.setProgress(Duration.ZERO);o.setLastTick(at);return;}Duration elapsed=o.getLastTick()==null?Duration.ZERO:Duration.between(o.getLastTick(),at);o.setLastTick(at);o.setProgress(o.getProgress().plus(elapsed));if(!o.getProgress().minus(config.getCaptureDuration()).isNegative()){o.setOwner(t);o.setOwnershipSince(at);o.setProgress(Duration.ZERO);o.setCapturingTeam(null);}}
 public int score(Team t){return scores.get(t);} public void addScore(Team t,int amount,Instant at){if(amount<0)throw new IllegalArgumentException();if(!isScoreLocked(t,at))scores.put(t,score(t)+amount);checkTarget();} private void checkTarget(){if(lifecycle.getPhase()==MatchPhase.ACTIVE)for(Team t:Team.values())if(score(t)>=config.getTargetScore()){resolve(t);break;}} private boolean isScoreLocked(Team t,Instant at){Instant x=scoreLocks.get(t);return x!=null&&x.isAfter(at);}
 public void recordKill(UUID k,UUID v,Instant at){Team kt=teams.get(k),vt=teams.get(v);if(kt==null||vt==null||kt==vt||at.isBefore(cooldowns.getOrDefault(v,Instant.MIN)))return;cooldowns.put(v,at.plus(config.getVictimCooldown()));addScore(kt,1,at);} public boolean recordCombat(UUID a,UUID v,Instant at){if(lifecycle.getPhase()!=MatchPhase.ACTIVE)return false;Team ta=teams.get(a),tv=teams.get(v);if(ta==null||tv==null||ta==tv||at.isBefore(spawnProtectedUntil.getOrDefault(a,Instant.MIN))||at.isBefore(spawnProtectedUntil.getOrDefault(v,Instant.MIN)))return false;recentCombat.put(a,at);recentCombat.put(v,at);return true;}
 public boolean recordDeath(UUID v,UUID k,Instant at){playerDied(v);boolean e=k!=null&&teams.get(k)!=null&&teams.get(v)!=null&&!teams.get(k).equals(teams.get(v))&&!at.isBefore(spawnProtectedUntil.getOrDefault(v,Instant.MIN))&&recentCombat.containsKey(k)&&recentCombat.containsKey(v)&&Duration.between(recentCombat.get(k),at).compareTo(config.getCombatWindow())<=0&&Duration.between(recentCombat.get(v),at).compareTo(config.getCombatWindow())<=0;if(e)recordKill(k,v,at);recentCombat.remove(v);return e;}
 public void deposit(UUID p,Resource r,int amount){Team t=teams.get(p);if(t==null)throw new IllegalStateException();int held=carried(p,r);if(amount<0||amount>held)throw new IllegalArgumentException();carried.computeIfAbsent(p,x->new EnumMap<>(Resource.class)).put(r,held-amount);storage.get(t).put(r,storage(t,r)+amount);} public void carry(UUID p,Resource r,int amount){if(amount<0)throw new IllegalArgumentException();carried.computeIfAbsent(p,x->new EnumMap<>(Resource.class)).put(r,carried(p,r)+amount);} public int carried(UUID p,Resource r){return carried.getOrDefault(p,Map.of()).getOrDefault(r,0);} public int storage(Team t,Resource r){return storage.get(t).get(r);} public void playerDied(UUID p){for(Resource r:Resource.values())carrySet(p,r,carried(p,r)/2);} private void carrySet(UUID p,Resource r,int n){carried.computeIfAbsent(p,x->new EnumMap<>(Resource.class)).put(r,n);}
 public void addBattleTokens(Team t,int a){if(a<0)throw new IllegalArgumentException();tokenWallet.put(t,tokenWallet.get(t)+a);} public int battleTokens(Team t){return tokenWallet.get(t);} public void purchaseArmory(UUID p,ArmoryItem i){Team t=teams.get(p);if(t==null)throw new IllegalStateException();int c=switch(i){case GATE_TIER_TWO->config.getGateTierTwoCost();case COMMAND_POST_TIER_TWO->config.getCommandPostTierTwoCost();case PROTECTION_WARD->config.getProtectionWardCost();case REPAIR->config.getRepairCost();};if(tokenWallet.get(t)<c)throw new IllegalArgumentException();tokenWallet.put(t,tokenWallet.get(t)-c);switch(i){case GATE_TIER_TWO->gates.get(t).setTier(Math.max(2,gates.get(t).getTier()));case COMMAND_POST_TIER_TWO->commandPostTier.put(t,2);case PROTECTION_WARD->activateWard(t,now.plus(config.getSuddenDeathDuration()));case REPAIR->gates.get(t).setHealth(100);}}
 public void activateWard(Team t,Instant until){wardUntil.put(t,until);for(OutpostState o:outposts.values()){o.setWardTeam(t);o.setWardUntil(until);}} public void summon(Team t,SummonKind k,OutpostId id){if(outposts.get(id).getOwner()!=t||summonsByTeam.get(t).size()>=config.getSummonCapPerTeam())throw new IllegalArgumentException();summonsByTeam.get(t).add(new Summon(t,k,id));} public List<Summon> summons(Team t){return List.copyOf(summonsByTeam.get(t));}
 public void disconnect(UUID p,Instant at){disconnected.put(p,at.plus(config.getDisconnectReservation()));} public boolean reconnect(UUID p,Instant at){Instant e=disconnected.get(p);if(e==null)return false;if(!at.isAfter(e)){disconnected.remove(p);return true;}expiredPlayers.add(p);return false;} private void expireDisconnects(Instant at){for(UUID p:new ArrayList<>(disconnected.keySet()))if(at.isAfter(disconnected.get(p))){expiredPlayers.add(p);disconnected.remove(p);playerDied(p);}}
 private void resolveAtDeadline(Instant at){int a=score(Team.A),b=score(Team.B);Team w=a!=b?(a>b?Team.A:Team.B):null;if(w==null){long ca=outposts.values().stream().filter(o->o.getOwner()==Team.A).count(),cb=outposts.values().stream().filter(o->o.getOwner()==Team.B).count();w=ca!=cb?(ca>cb?Team.A:Team.B):null;}if(w==null)suddenDeathUntil=at.plus(config.getSuddenDeathDuration());else resolve(w);} private void resolve(Team w){if(lifecycle.getPhase()==MatchPhase.ACTIVE){lifecycle.transitionTo(MatchPhase.RESOLVING);result=new MatchResult(w);}}
 public void resolveAndCleanup(Instant at){switch(lifecycle.getPhase()){case WAITING-> {return;}case PREPARING->lifecycle.transitionTo(MatchPhase.CLEANUP);case ACTIVE->{resolveAtDeadline(at);if(lifecycle.getPhase()==MatchPhase.ACTIVE&&suddenDeathUntil!=null)resolve(null);}default->{}}if(lifecycle.getPhase()==MatchPhase.RESOLVING)lifecycle.transitionTo(MatchPhase.CLEANUP);if(lifecycle.getPhase()!=MatchPhase.CLEANUP)return;lifecycle.transitionTo(MatchPhase.WAITING);for(UUID p:new ArrayList<>(teams.keySet()))roster.leave(p);teams.clear();expiredPlayers.clear();for(OutpostState o:outposts.values()){o.setOwner(null);o.setProgress(Duration.ZERO);o.setLastTick(null);o.setEmptySince(null);o.setCapturingTeam(null);o.setOwnershipSince(null);o.getOccupants().clear();o.setWardTeam(null);o.setWardUntil(null);}for(GateState g:gates.values()){g.setTier(1);g.setHealth(100);}for(Team t:Team.values()){scores.put(t,0);tokenWallet.put(t,0);commandPostTier.put(t,1);storage.get(t).replaceAll((r,v)->0);summonsByTeam.get(t).clear();}carried.clear();cooldowns.clear();disconnected.clear();spawnProtectedUntil.clear();recentCombat.clear();scoreLocks.clear();wardUntil.clear();portalClosedAt=null;suddenDeathUntil=null;battleStartedAt=null;now=at;nextScoreTick=at.plus(config.getScoreInterval());result=null;}
}
