package dev.jlo.gamemodes.arena;

import java.util.*;

public final class ArenaDefinition {
 private final String id,templateWorld; private final ArenaMode mode; private final Region bounds; private final List<Spawn> spawns; private final List<Objective> objectives; private final List<StructurePlacement> structures; private final List<ResourcePlacement> resources; private final List<SiegePlacement> siegePlacements;
 public ArenaDefinition(String id,ArenaMode mode,String templateWorld,Region bounds,List<Spawn> spawns,List<Objective> objectives,List<StructurePlacement> structures,List<ResourcePlacement> resources,List<SiegePlacement> siegePlacements){this.id=Objects.requireNonNull(id);this.mode=Objects.requireNonNull(mode);this.templateWorld=Objects.requireNonNull(templateWorld);this.bounds=Objects.requireNonNull(bounds);this.spawns=List.copyOf(spawns);this.objectives=List.copyOf(objectives);this.structures=List.copyOf(structures);this.resources=List.copyOf(resources);this.siegePlacements=List.copyOf(siegePlacements);if(id.isBlank())throw new IllegalArgumentException("Arena ID must not be blank");if(templateWorld.isBlank())throw new IllegalArgumentException("Template world must not be blank");if(!isSafeRelativePath(templateWorld))throw new IllegalArgumentException("Unsafe template world path");validate();}
 private static boolean isSafeRelativePath(String p){return !p.startsWith("/")&&!p.contains("\\")&&!Arrays.asList(p.split("/",-1)).contains("..");}
 public String getId(){return id;} public ArenaMode getMode(){return mode;} public String getTemplateWorld(){return templateWorld;} public Region getBounds(){return bounds;} public List<Spawn> getSpawns(){return spawns;} public List<Objective> getObjectives(){return objectives;} public List<StructurePlacement> getStructures(){return structures;} public List<ResourcePlacement> getResources(){return resources;} public List<SiegePlacement> getSiegePlacements(){return siegePlacements;}
 public void validate(){if(spawns.isEmpty())throw new IllegalArgumentException("Arena must define spawns");unique(spawns.stream().map(Spawn::id).toList(),"spawn");unique(objectives.stream().map(Objective::id).toList(),"objective");unique(structures.stream().map(StructurePlacement::id).toList(),"structure");unique(resources.stream().map(ResourcePlacement::id).toList(),"resource");unique(siegePlacements.stream().map(SiegePlacement::id).toList(),"siege placement");if(spawns.stream().noneMatch(s->s.team()==TeamSlot.A)||spawns.stream().noneMatch(s->s.team()==TeamSlot.B))throw new IllegalArgumentException("Arena must define a spawn for both teams");if(mode==ArenaMode.OPR){if(objectives.size()!=3)throw new IllegalArgumentException("OPR arena must define exactly 3 objectives");if(structures.stream().filter(s->s.kind()==StructureKind.GATE).count()<2||structures.stream().filter(s->s.kind()==StructureKind.COMMAND_POST).count()<2)throw new IllegalArgumentException("OPR arena must define both team structures");if(!siegePlacements.isEmpty())throw new IllegalArgumentException("OPR arena must not define siege placements");}else{if(objectives.size()!=3)throw new IllegalArgumentException("Siege arena must define exactly 3 objectives");if(structures.stream().noneMatch(s->s.kind()==StructureKind.GATE)||structures.stream().noneMatch(s->s.kind()==StructureKind.COMMAND_POST)||structures.stream().noneMatch(s->s.kind()==StructureKind.WALL))throw new IllegalArgumentException("Siege arena must define gate, command post, and wall structures");if(siegePlacements.isEmpty())throw new IllegalArgumentException("Siege arena must define siege placements");}spawns.forEach(s->{if(!bounds.contains(s.position()))throw new IllegalArgumentException("Spawn outside arena bounds");});objectives.forEach(o->{if(!within(o.region()))throw new IllegalArgumentException("Objective outside arena bounds");});structures.forEach(s->{if(!bounds.contains(s.position()))throw new IllegalArgumentException("Structure outside arena bounds");});resources.forEach(r->{if(!bounds.contains(r.position()))throw new IllegalArgumentException("Resource outside arena bounds");});siegePlacements.forEach(s->{if(!bounds.contains(s.position()))throw new IllegalArgumentException("Siege placement outside arena bounds");});for(int i=0;i<objectives.size();i++)for(int j=i+1;j<objectives.size();j++)if(objectives.get(i).region().overlaps(objectives.get(j).region()))throw new IllegalArgumentException("Objectives overlap");}
 private boolean within(Region r){return bounds.contains(new BlockPosition(r.getMinX(),r.getMinY(),r.getMinZ()))&&bounds.contains(new BlockPosition(r.getMaxX(),r.getMaxY(),r.getMaxZ()));} private static void unique(List<String> ids,String kind){if(ids.stream().anyMatch(String::isBlank))throw new IllegalArgumentException(kind+" IDs must not be blank");if(ids.size()!=new HashSet<>(ids).size())throw new IllegalArgumentException("Duplicate "+kind+" IDs");}
 public ArenaDefinition copy(String id,ArenaMode mode,String templateWorld,Region bounds,List<Spawn> spawns,List<Objective> objectives,List<StructurePlacement> structures,List<ResourcePlacement> resources,List<SiegePlacement> siegePlacements){return new ArenaDefinition(id,mode,templateWorld,bounds,spawns,objectives,structures,resources,siegePlacements);}
 @Override public boolean equals(Object o){return o instanceof ArenaDefinition a&&id.equals(a.id)&&mode==a.mode&&templateWorld.equals(a.templateWorld)&&bounds.equals(a.bounds)&&spawns.equals(a.spawns)&&objectives.equals(a.objectives)&&structures.equals(a.structures)&&resources.equals(a.resources)&&siegePlacements.equals(a.siegePlacements);} @Override public int hashCode(){return Objects.hash(id,mode,templateWorld,bounds,spawns,objectives,structures,resources,siegePlacements);} @Override public String toString(){return "ArenaDefinition(id="+id+", mode="+mode+", templateWorld="+templateWorld+", bounds="+bounds+", spawns="+spawns+", objectives="+objectives+", structures="+structures+", resources="+resources+", siegePlacements="+siegePlacements+")";}
}
